import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

/**
 * Generate PDF report from JSON content
 * @param {Object} reportContent - The JSON content of the report
 * @param {Object} storeInfo - Store information (name, industry)
 * @param {String} period - Period string (e.g. "2023-10-01 to 2023-10-07")
 * @returns {Promise<Buffer>} - The generated PDF buffer
 */
export function generatePDF(reportContent, storeInfo, period) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const buffers = [];

            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => {
                const pdfData = Buffer.concat(buffers);
                resolve(pdfData);
            });

            // --- Header ---
            doc.fontSize(20).text('Weekly Business Report', { align: 'center' });
            doc.moveDown();

            doc.fontSize(12).text(`Store: ${storeInfo.name}`, { align: 'left' });
            doc.text(`Industry: ${storeInfo.industry}`, { align: 'left' });
            doc.text(`Period: ${period}`, { align: 'left' });
            doc.moveDown();
            doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
            doc.moveDown();

            // --- Summary ---
            if (reportContent.summary) {
                doc.fontSize(16).text('Summary', { underline: true });
                doc.moveDown(0.5);
                doc.fontSize(12).text(reportContent.summary);
                doc.moveDown();
            }

            // --- KPI Analysis ---
            if (reportContent.kpi_analysis && reportContent.kpi_analysis.length > 0) {
                doc.fontSize(16).text('KPI Analysis', { underline: true });
                doc.moveDown(0.5);
                reportContent.kpi_analysis.forEach(point => {
                    doc.fontSize(12).text(`• ${point}`);
                });
                doc.moveDown();
            }

            // --- Issues ---
            if (reportContent.issues && reportContent.issues.length > 0) {
                doc.fontSize(16).text('Key Issues', { underline: true });
                doc.moveDown(0.5);
                reportContent.issues.forEach(issue => {
                    doc.fontSize(12).text(`• ${issue}`);
                });
                doc.moveDown();
            }

            // --- Actions ---
            if (reportContent.actions && reportContent.actions.length > 0) {
                doc.fontSize(16).text('Recommended Actions', { underline: true });
                doc.moveDown(0.5);
                reportContent.actions.forEach(action => {
                    doc.fontSize(12).text(`• ${action}`);
                });
                doc.moveDown();
            }

            // --- Forecast ---
            if (reportContent.forecast) {
                doc.fontSize(16).text('Next Week Forecast', { underline: true });
                doc.moveDown(0.5);
                doc.fontSize(12).text(`Revenue: ¥${reportContent.forecast.revenue?.toLocaleString() || '-'}`);
                doc.text(`Visitors: ${reportContent.forecast.visitors || '-'} people`);
                if (reportContent.forecast.reasoning) {
                    doc.moveDown(0.5);
                    doc.text(`Reasoning: ${reportContent.forecast.reasoning}`);
                }
            }

            // --- Footer ---
            doc.moveDown(2);
            doc.fontSize(10).text('Generated by Biz Insight AI', { align: 'center', color: 'grey' });

            doc.end();

        } catch (error) {
            reject(error);
        }
    });
}

export default { generatePDF };
